/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package light_out_inchaud_peaucelle;

import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Incha
 */
public class fenetredejeu extends javax.swing.JFrame {

    grille grillegraph=new grille();
    /**
     * Creates new form fenetredejeu
     */
    public fenetredejeu() {
        initComponents();
        
        for (int i = 0; i < 5; i++) {
            for (int a = 0; a < 5; a++) {
                int b=i;
                int d=a;
                casegraphique casep= new casegraphique(grillegraph.casejeu[i][a]);
                
                casep.addActionListener(new java.awt.event.ActionListener(){
                    public void actionPerformed(java.awt.event.ActionEvent evt){
                        Case c=casep.casegraph;
                        jouer(b,d);
                        panneaudejeu.repaint();
                        if (grillegraph.victoire()){
                            mode_normal.setEnabled(true);
                        }
                    }
                });
                panneaudejeu.add(casep);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneaudejeu = new javax.swing.JPanel();
        mode_normal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneaudejeu.setBackground(new java.awt.Color(255, 255, 255));
        panneaudejeu.setPreferredSize(new java.awt.Dimension(0, 0));
        panneaudejeu.setLayout(new java.awt.GridLayout(5, 5));
        getContentPane().add(panneaudejeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 480, 480));

        mode_normal.setLabel("Mode normal");
        mode_normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mode_normalActionPerformed(evt);
            }
        });
        getContentPane().add(mode_normal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 230, 70));

        setBounds(0, 0, 882, 532);
    }// </editor-fold>//GEN-END:initComponents

    private void mode_normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mode_normalActionPerformed
          // TODO add your handling code here:
          debuterpartie();
          panneaudejeu.repaint();
          mode_normal.setEnabled(false);
    }//GEN-LAST:event_mode_normalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetredejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetredejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetredejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetredejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetredejeu().setVisible(true);
            }
        });
    }
  public void debuterpartie() {
        Random generateurAleat = new Random();
        int nbrcasedebut = 1+generateurAleat.nextInt(15);
        for (int i = 0; i < nbrcasedebut; i++) {
            int randomx = generateurAleat.nextInt(4);
            int randomy = generateurAleat.nextInt(4);
            grillegraph.changementetat(randomx, randomy);
        }
        
    }
  
  public void jouer(int ligne, int colonne) {
        grillegraph.changementetat(ligne, colonne);
        if (colonne == 0) {
            grillegraph.changementetat(ligne, colonne + 1);
            if (ligne == 0) {
                grillegraph.changementetat(ligne + 1, colonne);
            } else if (ligne == 4) {
                grillegraph.changementetat(ligne - 1, colonne);
            } else {
                grillegraph.changementetat(ligne - 1, colonne);
                grillegraph.changementetat(ligne + 1, colonne);
            }
        } else if (colonne == 4) {
            grillegraph.changementetat(ligne, colonne - 1);
            if (ligne == 0) {
                grillegraph.changementetat(ligne + 1, colonne);
            } else if (ligne == 4) {
                grillegraph.changementetat(ligne - 1, colonne);
            } else {
                grillegraph.changementetat(ligne - 1, colonne);
                grillegraph.changementetat(ligne + 1, colonne);
            }
        }else if(ligne==0){
            grillegraph.changementetat(ligne+1, colonne);
            grillegraph.changementetat(ligne, colonne+1);
            grillegraph.changementetat(ligne, colonne-1);       
        }else if(ligne==4){
            grillegraph.changementetat(ligne-1, colonne);
            grillegraph.changementetat(ligne, colonne+1);
            grillegraph.changementetat(ligne, colonne-1);
        }else {
            grillegraph.changementetat(ligne-1, colonne);
            grillegraph.changementetat(ligne, colonne+1);
            grillegraph.changementetat(ligne, colonne-1);
            grillegraph.changementetat(ligne+1, colonne);
        }
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mode_normal;
    private javax.swing.JPanel panneaudejeu;
    // End of variables declaration//GEN-END:variables
}
